name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23'  # Or whatever version you need

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Set Git user identity
        run: |
          git config --global user.email "youremail@example.com"
          git config --global user.name "Your Name"

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
